<a href="https://colab.research.google.com/github/prasunr/PrasunGoogleColab/blob/master/Python_Edureka_Sep25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Python Basics**

In [ ]:
print("Hello World");
print("hello ma");
x =6
print(x)
print(id(x))
print(hex(id(x)))
print(type(x))

Hello World
hello ma
6
11642248
0xb1a588
<class 'int'>


In [ ]:
import keyword
print(keyword.kwlist)



['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [ ]:
str = "This is my first string"
print(str)
str2 = 'this is my first string'
print(str2)

This is my first string
this is my first string


In [ ]:
age=44
print(age<44)

False


In [ ]:
year=input('enter current year')
year = int(year)
print(year)
type(year)

enter current year2025
2025


int

In [ ]:
inputstring = input('enter a string')
print(inputstring)

enter a stringprasun
prasun


**Strings**

In [ ]:
str="12345"
print(str[::])
print(str[::1])
print(str[::-1])
print(str[::-2])

12345
12345
54321
531


ValueError: slice step cannot be zero

In [ ]:
#Reverse a string
str1 = 'abcd'
print(str1[::-1])


dcba


In [ ]:
mystr="my name is prasun"
print("prasun" in mystr)

True


In [ ]:
sample="my,name is prasun"
print(sample.split(","))

['my', 'name is prasun']


**Lists**

In [ ]:
lst=[10,20,30,40]
print(lst)
print(type(lst))

[10, 20, 30, 40]
<class 'list'>


In [ ]:
emp=[1001,'Amit Sharma',25000,'Jr.Manager',['project1', 'project2']]

In [ ]:
print(emp[0]) #Reference elements by [index]
print("Length of List",len(emp)) #Gets length of List
emp[0]=1002 #List is Mutable
emp[1]=1002 #List can have duplicates
print(emp)

1002
Length of List 5
[1002, 1002, 25000, 'Jr.Manager', ['project1', 'project2']]


In [ ]:
emp.append('test')
emp.extend(['test2','test3'])
emp.insert(0, 'test4')
print(emp)

['test4', 1002, 1002, 25000, 'Jr.Manager', ['project1', 'project2'], 'test', 'test', 'test2', 'test3', 'test', 'test2', 'test3']


In [ ]:
emp.pop()
print(emp)
emp.remove('test2')
print(emp)

['test4', 1002, 1002, 25000, 'Jr.Manager', ['project1', 'project2'], 'test', 'test', 'test2', 'test3', 'test']
['test4', 1002, 1002, 25000, 'Jr.Manager', ['project1', 'project2'], 'test', 'test', 'test3', 'test']


In [ ]:
#Join two or more lists
lst1=[1,2,3]
lst2=[4,5,6]
lst3=lst1+lst2
print(lst3)

[1, 2, 3, 4, 5, 6]


In [ ]:
#Membership operator
print(1 in lst2)
print(1 not in lst2)

False
True


In [ ]:
#List Comprehensions
lst=[45,96,85,74,52,35,95,67]
lstFilter=[i*2 for i in lst]
print(lstFilter)

lstFilter2=[i for i in lst if i%2==0]
print(lstFilter2)



[90, 192, 170, 148, 104, 70, 190, 134]
[96, 74, 52]


**Tuples**

In [ ]:
#Tuple(10,20,30): ordered, Immutable, allow duplicates

tup=(10,20,30)
print(tup)
print(type(tup))
print(tup[0])

(10, 20, 30)
<class 'tuple'>
10


In [ ]:
#immutable tuple
tup[0]=100

TypeError: 'tuple' object does not support item assignment

In [ ]:
tup=(10,20,20,30,50)
print(tup.count(20))
print(tup.index(20))
print(40 in tup)

2
1
False


**Sets**

In [ ]:
#Set {10,20,30} - unordered, mutable, DO NOT ALLOW DUPLICATES

mySet={40,20,10,30,30,30}
print(mySet)
print(type(mySet))

{40, 10, 20, 30}
<class 'set'>


In [ ]:
#set will automatically remove duplicates
print(mySet)

{40, 10, 20, 30}


In [ ]:
#set will not allow indexes [i]
print(mySet[0])

TypeError: 'set' object is not subscriptable

In [ ]:
mySet2={'one','one','two','three','one'}
print(mySet2)

{'two', 'three', 'one'}


In [ ]:
#membership in a set
print('one' in mySet2)

True


In [ ]:
#Add and Remove items to a set
mySet2.add('four')
print(mySet2)

{'two', 'four', 'three', 'one'}


In [ ]:
#Duplicate values are never allowed even if you add via Update() method
mySet2.update([10,20, 'five','six'])
print(mySet2)

{10, 'one', 'two', 20, 'three', 'five', 'six', 'four'}


In [ ]:
#Set theory operations (union, intersection, etc)
set1={1,2,3,4,5}
set2={4,5,6,7,8}
print(set1.union(set2))
print(set1.intersection(set2))
print(set1.difference(set2))
#or
print(set1|set2)
print(set1&set2)
print(set1-set2)

{1, 2, 3, 4, 5, 6, 7, 8}
{4, 5}
{1, 2, 3}
{1, 2, 3, 4, 5, 6, 7, 8}
{4, 5}
{1, 2, 3}


**Dictionary**

In [ ]:
#Dictionary{key:value}: unordered, keys are immutable, values are mutable. Keys cannot be duplicate but values can be.

In [ ]:
empDictionary={'id':1001,'name':'Amit Sharma','salary':25000}
print(empDictionary)
print(type(empDictionary))

{'id': 1001, 'name': 'Amit Sharma', 'salary': 25000}
<class 'dict'>


In [ ]:
print(empDictionary['name'])

Amit Sharma


In [ ]:
# Keys are immutable and unique, which means you cannot modify the key in a
# dictionary. %%

In [ ]:
#IF and ELSE
num =2
if num > 0:
  print('yes')

num1 = 3
if num1> 0:
  print('yes')
else:
  print('no')

yes
yes


In [ ]:
#Match-case (slightly faster than if else)
char='b'
match char:
  case 'a':
    print('yes')
  case _:
    print('no')

no


In [ ]:
#For
my_dict={'id':1001,'name':'Amit Sharma','salary':25000}
for i in my_dict:
  print(my_dict[i])


1001
Amit Sharma
25000


In [ ]:
#enumerate()
lst=[7,8,9,10]
for i in enumerate(lst):
  print(i)

my_dict={'id':1001,'name':'Amit Sharma','salary':25000}
for i in enumerate(my_dict):
  print(i)

(0, 7)
(1, 8)
(2, 9)
(3, 10)
(0, 'id')
(1, 'name')
(2, 'salary')


In [ ]:
#while loop

i=1
while i<=10:
  print(i)
  i+=1

1
2
3
4
5
6
7
8
9
10


In [ ]:
#range(start, stop, step): allows you to create a list of elements in a sequence/interval
print(list(range(1,10,2)))
print(list(range(10)))

[1, 3, 5, 7, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


**Functions**

In [ ]:
# Function
def helloPerson(name):
  print(f"Hello {name} how are you?")

# Call the function
helloPerson("Prasun")



Hello Prasun how are you?


In [ ]:
# Function with two arguments
def FunctionWithTwoArguments(name, age):
  print(f" Hello {name}, your age is {age}")

# Call the function
FunctionWithTwoArguments("Prasun", 44)




 Hello Prasun, your age is 44


In [ ]:
# Function that returns
def funcThatReturns(salary):
  tax = (salary*10)/100
  return tax

  tax_to_be_paid = funcThatReturns(25000)
  print(tax_to_be_paid)

In [ ]:
# Function that retusn multiple values
def funcThatReturnsMultiple(var1, var2):
  return var1, var2

  var1_returned, var2_returned = funcThatReturnsMultiple(10,20)
  print(f" var1 is {var1_returned}")
  print(f" var2 is {var2_returned}")

In [ ]:
# Types of Arguments

#1 Required Positional arguments
#-----------------------------------------
# means arguments are required and also the position matters. Can't pass wrong
def funcWithArg(name, year):
  print(f"Hi, {name} you are {year} years old")

funcWithArg("Prasun", 44)

Hi, Prasun you are 44 years old


In [ ]:
#2 Keyword arguments
#----------------------------------------
# HIGHLY PREFERED METHOD
funcWithArg(name="MichaeL", year=1991)
# ALSO ORDER DOES NOT MATTER HERE
funcWithArg(year=2022,name="dj")

Hi, MichaeL you are 1991 years old
Hi, dj you are 2022 years old


In [ ]:
#3 Default or optional arguments
#-------------------------------------------
def funcWithDefaultArg(name, year=1991):
  print(f"Hi, {name} you are {year} years old")
funcWithDefaultArg("prasun")

Hi, prasun you are 1991 years old


In [ ]:
#4 Variable-length/Arbitary arguments(*args, **kwargs)
#---------------------------------------------
def func4(*names): #Arbitary arguments
  for name in names:
    print(f"Hi, {name}")

func4("prasun", "ac/dc")

#key-arbitary argument
def func5(**employee_details): #key arbitary argument
  print(employee_details)

func5(id=1001,name="praun")

Hi, prasun
Hi, ac/dc
{'id': 1001, 'name': 'praun'}


In [ ]:
#Lambda functions
#one-line functions defined using the lambda keyword.
#They don't need a name.
#They don't allow lot of logic
result = lambda year:print(f"this is {year}")

#Method 1 to call Lambda
print(result("1999"))


this is 1999
None


In [ ]:
#Method 2 to call lambda
print((lambda year:print(f"this is {year}"))("1991"))

this is 1991
None


In [ ]:
# Class

class Student:
    def __init__(self, name, roll_no):
      self.name = name
      self.roll_no = roll_no
      print("Constructor called")

stud1 = Student("prasun", 1001)
print(stud1.name)
print(stud1.roll_no)

Constructor called
prasun
1001


In [ ]:
# Encapsulation
# Access Modifiers/specifiers: public, private and protected
# By default all variables are public
# __<variable> (double underscore before) means it's a private variable
# _<variable> (single underscore before) means it's a protected variable
class Account:
  def __init__(self, owner, balance):
    self.owner = owner       #public attibute
    self.__balance = balance #private attribute

  def deposit(self, amount):
    self.__balance += amount

  def get_balance(self):
    return self.__balance

acc1 = Account("prasun", 10000)
acc1.deposit(500)
print(acc1.get_balance())
#print(acc1.__balance) will give a compile error.


10500


In [ ]:
# Inheritance
class Animal:
  def speak(self):
    print("Animal makes a sound")

class Dog(Animal):
  def bark(self):
    print("Dog barks")

dog = Dog()
dog.bark()
dog.speak()



Dog barks
Animal makes a sound


In [ ]:
# Multiple Inheritance
class A:
  def feature1(self):
    print("Feature A")

class B:
  def feature2(self):
    print("Feature B")

class C(A,B):
  pass  # empty statement - we don't have anything to do.

# telling the interpreter that i'm inheriting both the classes A and B.
c = C()
c.feature1()
c.feature2()


Feature A
Feature B


In [ ]:
class A:
  def feature1(self):
    print("Feature A")

class B:
  def feature2(self):
    print("Feature B")

class C(A,B):
  def feature3(self):
    print("Feature C")

obj2 = C()
obj2.feature1()
obj2.feature2()
obj2.feature3()


Feature A
Feature B
Feature C


In [ ]:
#DIY Polymorphism

#DIY Method Overriding



In [ ]:
# Exception Handling
# To handle exceptions, we use
# Try, except, finally
import sys

try:
  var4 = int(input("Enter a number4: "))
  var5 = int(input("Enter a number5: "))
  var6 = var4/var5
  print(var6)

except ValueError:
  print("Invalid input")
  print(sys.exc_info())
except ZeroDivisionError:
  print("Zero division error")
  print(sys.exc_info())
finally:
  print("i'm inside Finally block")

#import sys module and call
#sys.exc_info()


Enter a number4: 33
Enter a number5: 0
Zero division error
(<class 'ZeroDivisionError'>, ZeroDivisionError('division by zero'), <traceback object at 0x7dc37e658740>)
Finally block


**Python Libraries/Modules**

In [ ]:
Mathematical operations - math, numpy
Data analysis - pandas
Visualization - matplotlib, seaborn
ML - scikit-learn, tensorflow
Web development - flask, django

numpy - numpy.org

In [ ]:
#numpy etc libraries need to be installed separately.
#lucikly in ide like google colab its already available.

#How to install if you are not using colab ?
!pip install numpy

**Numpy**


Provides powerful N-dimensional arrays and math functions.

In [ ]:
#Create numpy array
import numpy as np
# as np is alias. Instead of calling numpy. etc use np.
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

# We cannot store hetrogenious datatypes in numpy.
# all datatypes should be same.



[1 2 3 4 5]
<class 'numpy.ndarray'>
int64


In [ ]:
#.dtype will give you the datatype of a numpy array
print(arr.dtype)


int64


In [ ]:
#arange(start, stop, step) here start is inclusive, stop is not.
arr = np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [ ]:
#Random array methods .rand() and .randint(start, stop, size or len of array)
arr = np.random.rand(5)
print(arr)
arrInt = np.random.randint(1,100,5)
print(arrInt)

[0.13237946 0.00435678 0.13883101 0.00753668 0.06053432]
[85 76 24 75 87]


In [ ]:
#Create 2D array - make sure you have same number of columns in all rows. I.e here all rows should have 3 columns.
arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr)

#.ndim returns 2 for 2 dimensional array
print(arr.ndim)

#.shape returns rows and columns in parenthesis like this: (rows, columns)
print(arr.shape)

#How to access elements in a 2d array
print(arr[0][1])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
2
(3, 3)
20


In [ ]:
# Matrix Multiplication - is done using .dot()
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[10,11],[20,21],[30,31]])
print(arr1) # 2X3
print(arr2) # 3X2
print(np.dot(arr1,arr2)) #Output will be 2x2

[[1 2 3]
 [4 5 6]]
[[10 11]
 [20 21]
 [30 31]]
[[140 146]
 [320 335]]


In [ ]:
# Reshape() - reshape a matrix
arr = np.array([40,50,60,70,80,90])
# Reshape it to 2x3
arr_new = arr.reshape(3,2)
print(arr_new)

arr_new = arr.reshape(3,2)
print(arr_new)

#IMPORTANT
# we cannot go against the size of the array
# we cannot have something like
arr_new = arr.reshape(3,3) # has 9 elements but we only have 6 elements
print(arr_new)


[[40 50]
 [60 70]
 [80 90]]
[[40 50]
 [60 70]
 [80 90]]


ValueError: cannot reshape array of size 6 into shape (3,3)

In [ ]:
# Transpose
print(arr_new)
print(np.transpose(arr_new))
# Rows become columns, and columns become rows

[[40 50]
 [60 70]
 [80 90]]
[[40 60 80]
 [50 70 90]]


In [ ]:
# Broadcasting of Arithmetic Operations
lst = [10,20,30]
print(lst*5)

arr = np.array([10,20,30])
print(arr*5)

[10, 20, 30, 10, 20, 30, 10, 20, 30, 10, 20, 30, 10, 20, 30]
[ 50 100 150]


In [ ]:
# Stats Functions
sales = np.array([456,123,789,489, 453])
print("Total Sales:", sales.sum())
print("Min sales: ", sales.min())
print("Max sales: ", sales.max())
print("Mean sales: ", sales.mean())
print("Median sales: ", np.median(sales))
print("Standard Deviation: ", sales.std())
print("Variance: ", sales.var())

Total Sales: 2310
Min sales:  123
Max sales:  789
Mean sales:  462.0
Median sales:  456.0
Standard Deviation:  211.04312355535302
Variance:  44539.2


**Pandas** Data manipulation

[pandas documentation](https://pandas.pydata.org)

A fast powerful flexible and easy to use open source data analysis and manipulation tool, built on top of Python programming language.



Pandas uses two main structures to store data:
1. Series (1D data)
2. DataFrame (2D tabular data)


In [ ]:
#Import Data into Dataframe
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/pandas-dev/pandas/master/doc/data/titanic.csv")
print(df)


     PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                                Heikkinen, Miss Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ... 

In [ ]:
# .head() => Get top 5 rows by default. head(10) => get top 10 rows
# .tail() => Get bottom 5 rows by default. tail(10) => get bottom 10 rows
print(df.head())

#Get top 5 by default

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                              Heikkinen, Miss Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  


In [ ]:
# .info() => Get All Column data types and null values
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None


In [ ]:
# .describe() => Statistical Summary
print(df.describe())

       PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200  


In [ ]:
print(df['Name'].describe())

count                     891
unique                    891
top       Dooley, Mr. Patrick
freq                        1
Name: Name, dtype: object


Selections: specific rows, columns



In [ ]:

#Select specific Rows

#Before getting a specific row, set a primary key or specific index

#Set an index to get a specific row


print(df.head(15))
if "PassengerId" in df.columns:
    df = df.set_index("PassengerId")

print(df.index.name)




             Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   
6                   0       3   
7                   0       1   
8                   0       3   
9                   1       3   
10                  1       2   
11                  1       3   
12                  1       1   
13                  0       3   
14                  0       3   
15                  0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                        Heikkinen, Miss Laina  female  26.0   
4                 Futrelle, Mrs. Jacqu

In [ ]:
# .reset_index().set_index()
# Alternative way by hard reset index

df = df.reset_index().set_index("PassengerId")
print(df.index.name)

PassengerId


In [ ]:
# .at()
# can only pass one column
print(df.at[1, "Name"])
#

Braund, Mr. Owen Harris


In [ ]:
# .loc()
# you pass .loc('index1', 'index2', 'index3')
print(df.loc[[1,2,3]])


             Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                        Heikkinen, Miss Laina  female  26.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
                                                          Name     Ticket
Passenger

In [ ]:

# .loc() with where clause where you pass other column names
print(df.loc[[1,2],['Name','Ticket']])

                                                          Name     Ticket
PassengerId                                                              
1                                      Braund, Mr. Owen Harris  A/5 21171
2            Cumings, Mrs. John Bradley (Florence Briggs Th...   PC 17599


In [ ]:
# .loc() with range
print(df.loc[4:9])

             Survived  Pclass  \
PassengerId                     
4                   1       1   
5                   0       3   
6                   0       3   
7                   0       1   
8                   0       3   
9                   1       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   
6                                             Moran, Mr. James    male   NaN   
7                                      McCarthy, Mr. Timothy J    male  54.0   
8                                Palsson, Master Gosta Leonard    male   2.0   
9            Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0   

             SibSp  Parch  Ticket     Fare Cabin Embarked  
PassengerId                       